### ISSUE TITLE
Allow secret params that are not logged

### ISSUE THREAD

**Issue by tobiiasl** [for-GET/katt#70]
Allow some way of specifying secret params that should not be printed to stdout, e.g. params starting with underscore.

The benefits would be:
1) Avoid having secrets such as passwords or tokens appearing in logs.
2) Avoid having logs flooded with huge tokens.

Regarding benefit 2: In our case we we specify 4 different jwt tokens as params to KATT. They are each 940 chars and they appear 3 times each in the log (also in final_params and transaction_results). That is roughly 12K chars printed for each KATT file. We have roughly 10 KATT files so that is 120K chars in the log files for each test run.

**Comment by andreineculau** [comment]
it's close to impossible because KATT would not be aware of all the places where params show up e.g. they might be part of a response

but it should be possible for the KATT-caller to use `sed`&co for that thanks to bash's pipe substitution e.g. `katt 2> >(sed "s/my-pass/xxx/g" 1>&2) | sed "s/my-pass/xxx/g"` (obviously `sed "s/my-pass/xxx/g"` could be substituted  with a more complex shell script)
